In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv("Amazon.csv")

In [69]:
df.head(5)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,1/31/2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,12/30/2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon pay,Delivered,Fort Worth,TX,United states,SELL01298
2,ORD0000003,5/10/2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit card,Delivered,Austin,TX,United states,SELL00908
3,ORD0000004,7/18/2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2/4/2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit card,Cancelled,San Antonio,TX,Canada,SELL01411

In [35]:
df.shape

(100000, 20)

In [36]:
df.size

2000000

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  str
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    99962 non-null   float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: float64(5), int64(1), str(14)
memory usage: 15.3 MB

In [38]:
df.isnull().sum()

OrderID           0
OrderDate         0
CustomerID        0
CustomerName      0
ProductID         0
ProductName       0
Category          0
Brand             0
Quantity          0
UnitPrice         0
Discount          0
Tax               0
ShippingCost      0
TotalAmount      38
PaymentMethod     0
OrderStatus       0
City              0
State             0
Country           0
SellerID          0
dtype: int64

In [70]:
df.isnull().sum().sum()

np.int64(0)

In [39]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='str')

In [40]:
df["TotalAmount"] = df["TotalAmount"].fillna(((df["Quantity"]*df["UnitPrice"])-((df["Quantity"]*df["UnitPrice"])*df["Discount"]))+
                                             (df["Tax"]+df["ShippingCost"]))

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  str
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: float64(5), int64(1), str(14)
memory usage: 15.3 MB

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df["OrderID"].duplicated().sum()

np.int64(0)

In [44]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='str')

In [53]:
for i in df.columns:
    if df[i].nunique() < 50:
        print(df[i].value_counts())
        print("-"*50)

Category
Electronics          16853
Sports & Outdoors    16804
Books                16752
Home & Kitchen       16610
Toys & Games         16542
Clothing             16439
Name: count, dtype: int64
--------------------------------------------------
Brand
ReadMore      10204
FitLife       10147
CoreTech      10127
KiddoFun      10077
Zenith         9990
NexPro         9962
Apex           9937
BrightLux      9907
UrbanStyle     9854
HomeEase       9795
Name: count, dtype: int64
--------------------------------------------------
Quantity
4    20056
2    20014
3    19995
5    19992
1    19943
Name: count, dtype: int64
--------------------------------------------------
Discount
0.00    40246
0.05    19889
0.10    14910
0.15    10041
0.20     7939
0.25     4986
0.30     1989
Name: count, dtype: int64
--------------------------------------------------
PaymentMethod
Credit Card         34944
Debit Card          20024
UPI                 14947
Amazon Pay          14836
Net Banking          9927
Cash on Delivery     4776
upi                   119
CC                     94
ap                     90
cod                    86
amazon PAY             66
COD                    66
AP                     25
Name: count, dtype: int64
--------------------------------------------------
OrderStatus
Delivered    74628
Shipped      15192
Pending       4103
Returned      3049
Cancelled     3028
Name: count, dtype: int64
--------------------------------------------------
City
Charlotte        5110
Jacksonville     5107
San Jose         5107
Dallas           5105
Los Angeles      5058
Austin           5043
Seattle          5039
Washington       5021
Columbus         5021
Chicago          5020
Philadelphia     5014
Denver           4991
Indianapolis     4970
New York         4949
Phoenix          4941
Fort Worth       4934
San Francisco    4930
San Antonio      4913
Houston          4901
San Diego        4826
Name: count, dtype: int64
--------------------------------------------------
State
TX    24896
CA    19921
NC     5110
FL     5107
WA     5039
DC     5021
OH     5021
IL     5020
PA     5014
CO     4991
IN     4970
NY     4949
AZ     4941
Name: count, dtype: int64
--------------------------------------------------
Country
United States     69900
India             14915
Canada             5818
United Kingdom     4789
Australia          4130
US                  158
UK                  154
iNDIA               136
Name: count, dtype: int64
--------------------------------------------------

In [55]:
df["PaymentMethod"] = df["PaymentMethod"].str.capitalize()

In [56]:
df["PaymentMethod"].value_counts()

PaymentMethod
Credit card         34944
Debit card          20024
Upi                 15066
Amazon pay          14902
Net banking          9927
Cash on delivery     4776
Cod                   152
Ap                    115
Cc                     94
Name: count, dtype: int64

In [59]:
df["PaymentMethod"] = df["PaymentMethod"].replace({"Upi" : "UPI", "Cod" : "Cash on delivery", "Ap" : "Amazon pay","Cc" : "Credit card"})

In [60]:
df["PaymentMethod"].value_counts()

PaymentMethod
Credit card         35038
Debit card          20024
UPI                 15066
Amazon pay          15017
Net banking          9927
Cash on delivery     4928
Name: count, dtype: int64

In [62]:
df["Country"] = df["Country"].str.capitalize()

In [63]:
df["Country"].value_counts()

Country
United states     69900
India             15051
Canada             5818
United kingdom     4789
Australia          4130
Us                  158
Uk                  154
Name: count, dtype: int64

In [64]:
df["Country"] = df["Country"].replace({"Us" : "United states", "Uk" : "United Kingdom"})

In [65]:
df["Country"].value_counts()

Country
United states     70058
India             15051
Canada             5818
United kingdom     4789
Australia          4130
United Kingdom      154
Name: count, dtype: int64

In [66]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [67]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OrderID,100000,100000,ORD0000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OrderDate,100000,1825,4/28/2022,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerID,100000,43233,CUST023748,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerName,100000,200,Karan Joshi,556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProductID,100000,50,P00019,2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProductName,100000,50,LED Desk Lamp,2098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,100000,6,Electronics,16853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand,100000,10,ReadMore,10204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,100000.0,NaN,NaN,NaN,3.0014,1.413548,1.0,2.0,3.0,4.0,5.0
UnitPrice,100000.0,NaN,NaN,NaN,302.905748,171.840797,5.0,154.19,303.07,451.5,599.99
Discount,100000.0,NaN,NaN,NaN,0.074226,0.082583,0.0,0.0,0.05,0.1,0.3
Tax,100000.0,NaN,NaN,NaN,68.468902,74.13118,0.0,15.92,45.25,96.06,538.46
ShippingCost,100000.0,NaN,NaN,NaN,7.40666,4.324057,0.0,3.68,7.3,11.15,15.0
TotalAmount,100000.0,NaN,NaN,NaN,918.256479,724.508332,4.27,340.89,714.315,1349.765,3534.98
PaymentMethod,100000,6,Credit card,35038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OrderStatus,100000,5,Delivered,74628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,100000,20,Charlotte,5110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,100000,13,TX,24896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,100000,6,United states,70058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SellerID,100000,1999,SELL01099,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
print("1. Missing values:")
print(df.isnull().sum())

print("\n2. Total missing values:")
print(df.isnull().sum().sum())

print("\n3. Duplicate rows:")
print(df.duplicated().sum())

print("\n4. Duplicate Order IDs:")
print(df["OrderID"].duplicated().sum())

print("\n5. Payment method values:")
print(df["PaymentMethod"].value_counts())

print("\n6. Country values:")
print(df["Country"].value_counts())

print("\n7. OrderDate data type:")
print(df["OrderDate"].dtype)

1. Missing values:
OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

2. Total missing values:
0

3. Duplicate rows:
0

4. Duplicate Order IDs:
0

5. Payment method values:
PaymentMethod
Credit card         35038
Debit card          20024
UPI                 15066
Amazon pay          15017
Net banking          9927
Cash on delivery     4928
Name: count, dtype: int64

6. Country values:
Country
United states     70058
India             15051
Canada             5818
United kingdom     4789
Australia          4130
United Kingdom      154
Name: count, dtype: int64

7. OrderDate data type:
str

In [73]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [76]:
df["OrderDate"].dtype

dtype('<M8[us]')

In [78]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='str')

In [85]:
# Which product category generates the highest total sales?
df.groupby("Category")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

Category
Electronics    15584217.0
Name: TotalAmount, dtype: float64

In [87]:
# Which payment method generates the highest total sales?
df.groupby("PaymentMethod")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

PaymentMethod
Credit card    32122159.0
Name: TotalAmount, dtype: float64

In [89]:
# Which countries generate the highest total sales?
df.groupby("Country")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

Country
United states    64310049.0
Name: TotalAmount, dtype: float64

In [93]:
# Which product brands generate the highest total sales?
df.groupby("Brand")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

Brand
CoreTech    9343721.0
Name: TotalAmount, dtype: float64

In [94]:
# Which cities generate the highest total sales?
df.groupby("City")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

City
Charlotte    4747702.0
Name: TotalAmount, dtype: float64

In [95]:
#Which states generate the highest total sales?
df.groupby("State")["TotalAmount"].sum().round().sort_values(ascending = False).head(1)

State
TX    22862541.0
Name: TotalAmount, dtype: float64

In [98]:
# How do total sales change month by month?
df.groupby(df["OrderDate"].dt.to_period("M"))["TotalAmount"].sum().round().sort_index()

OrderDate
2020-01    1637069.0
2020-02    1339388.0
2020-03    1587126.0
2020-04    1588347.0
2020-05    1533834.0
2020-06    1500269.0
2020-07    1552982.0
2020-08    1640875.0
2020-09    1554682.0
2020-10    1515404.0
2020-11    1502232.0
2020-12    1577655.0
2021-01    1575253.0
2021-02    1425366.0
2021-03    1484166.0
2021-04    1470885.0
2021-05    1571842.0
2021-06    1593398.0
2021-07    1596668.0
2021-08    1545324.0
2021-09    1534912.0
2021-10    1511118.0
2021-11    1419481.0
2021-12    1520160.0
2022-01    1609760.0
2022-02    1369866.0
2022-03    1589809.0
2022-04    1515497.0
2022-05    1527845.0
2022-06    1533830.0
2022-07    1556516.0
2022-08    1541701.0
2022-09    1457860.0
2022-10    1534350.0
2022-11    1525937.0
2022-12    1604276.0
2023-01    1567772.0
2023-02    1384957.0
2023-03    1557147.0
2023-04    1560322.0
2023-05    1588152.0
2023-06    1485367.0
2023-07    1562299.0
2023-08    1585425.0
2023-09    1543307.0
2023-10    1573039.0
2023-11    1518312.0
2023-12    1587814.0
2024-01    1493947.0
2024-02    1412147.0
2024-03    1548280.0
2024-04    1511152.0
2024-05    1642610.0
2024-06    1541772.0
2024-07    1469460.0
2024-08    1577273.0
2024-09    1468210.0
2024-10    1520333.0
2024-11    1529791.0
2024-12    1451074.0
Freq: M, Name: TotalAmount, dtype: float64

In [99]:
# Total sales by order status
df.groupby("OrderStatus")["TotalAmount"].sum().round()

OrderStatus
Cancelled     2851122.0
Delivered    68372677.0
Pending       3737557.0
Returned      2780662.0
Shipped      14083629.0
Name: TotalAmount, dtype: float64

In [102]:
# Top 10 products by total sales
df.groupby("ProductName")["TotalAmount"].sum().round().sort_values(ascending = False).head(10)

ProductName
Memory Card 128GB      1935138.0
LED Desk Lamp          1921948.0
Mechanical Keyboard    1906964.0
Electric Kettle        1905752.0
Smartwatch             1901276.0
Dress Shirt            1896765.0
Water Bottle           1895468.0
Gaming Mouse           1895104.0
Kids Toy Car           1891082.0
Jeans                  1882592.0
Name: TotalAmount, dtype: float64

In [103]:
# Top 10 customers by total sales
df.groupby("CustomerName")["TotalAmount"].sum().round().sort_values(ascending = False).head(10)

CustomerName
Pooja Kapoor    547833.0
Vihaan Singh    526676.0
Pooja Singh     516451.0
Kabir Joshi     515362.0
Aditya Gupta    515005.0
Mohit Singh     513513.0
Sunita Mehta    511643.0
Aman Reddy      511237.0
Karan Singh     510901.0
Simran Singh    509337.0
Name: TotalAmount, dtype: float64

In [105]:
# Average order amount by product category
df.groupby("Category")["TotalAmount"].mean().round(2)

Category
Books                911.05
Clothing             927.88
Electronics          924.71
Home & Kitchen       912.94
Sports & Outdoors    913.21
Toys & Games         919.88
Name: TotalAmount, dtype: float64

In [107]:
# Total quantity sold by product category
df.groupby("Category")["Quantity"].sum().round(2)

Category
Books                49981
Clothing             49523
Electronics          50696
Home & Kitchen       49624
Sports & Outdoors    50543
Toys & Games         49773
Name: Quantity, dtype: int64

In [108]:
# Average discount by product category
df.groupby("Category")["Discount"].mean()

Category
Books                0.073896
Clothing             0.073970
Electronics          0.074340
Home & Kitchen       0.075084
Sports & Outdoors    0.074000
Toys & Games         0.074066
Name: Discount, dtype: float64

In [109]:
# Average unit price by product category
df.groupby("Category")["UnitPrice"].sum()

Category
Books                5059492.24
Clothing             5017123.85
Electronics          5105225.81
Home & Kitchen       5028913.29
Sports & Outdoors    5070734.27
Toys & Games         5009085.38
Name: UnitPrice, dtype: float64

In [110]:
# Total tax by product category
df.groupby("Category")["Tax"].sum()

Category
Books                1141818.38
Clothing             1133007.73
Electronics          1170203.54
Home & Kitchen       1138887.15
Sports & Outdoors    1139056.82
Toys & Games         1123916.54
Name: Tax, dtype: float64

In [111]:
# Total shipping cost by product category
df.groupby("Category")["ShippingCost"].sum()

Category
Books                123604.49
Clothing             121538.22
Electronics          125399.94
Home & Kitchen       122880.71
Sports & Outdoors    124523.57
Toys & Games         122719.08
Name: ShippingCost, dtype: float64

In [112]:
# Number of orders by payment method
df.groupby("PaymentMethod")["OrderID"].count()

PaymentMethod
Amazon pay          15017
Cash on delivery     4928
Credit card         35038
Debit card          20024
Net banking          9927
UPI                 15066
Name: OrderID, dtype: int64

In [116]:
# Which brands have the highest total quantity of products sold?
df.groupby("Brand")["Quantity"].sum().sort_values(ascending = False).head(1)

Brand
CoreTech    30430
Name: Quantity, dtype: int64

In [120]:
# How does the number of unique orders change month by month?
df.groupby(df["OrderDate"].dt.to_period("M"))["OrderID"].count().sort_index()

OrderDate
2020-01    1730
2020-02    1490
2020-03    1685
2020-04    1692
2020-05    1672
2020-06    1633
2020-07    1687
2020-08    1783
2020-09    1679
2020-10    1647
2020-11    1639
2020-12    1729
2021-01    1764
2021-02    1516
2021-03    1620
2021-04    1594
2021-05    1716
2021-06    1668
2021-07    1718
2021-08    1704
2021-09    1674
2021-10    1672
2021-11    1587
2021-12    1657
2022-01    1744
2022-02    1510
2022-03    1710
2022-04    1636
2022-05    1709
2022-06    1690
2022-07    1689
2022-08    1717
2022-09    1645
2022-10    1633
2022-11    1642
2022-12    1753
2023-01    1721
2023-02    1540
2023-03    1683
2023-04    1641
2023-05    1709
2023-06    1650
2023-07    1712
2023-08    1733
2023-09    1665
2023-10    1660
2023-11    1656
2023-12    1726
2024-01    1679
2024-02    1562
2024-03    1740
2024-04    1647
2024-05    1753
2024-06    1671
2024-07    1631
2024-08    1731
2024-09    1613
2024-10    1642
2024-11    1624
2024-12    1577
Freq: M, Name: OrderID, dtype: int64

In [123]:
df.to_csv("Amazon.csv", index = False)

In [124]:
%pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.1.5-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\saroj\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.1.5-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 2.5 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.4 MB 2.8 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 2.8 MB/s  0:00:01
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: sqlalchemy, pymysql

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [pymysql]
   ---------------------------------------- 2/2 [pymysql]

Successfully installed pymysql-1.2.3 sqlalchemy-2.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [126]:
from sqlalchemy import create_engine
from getpass import getpass
from urllib.parse import quote_plus

username = "root"  # Change if your MySQL username differs
password = getpass("Enter your MySQL password: ")

engine = create_engine(
    f"mysql+pymysql://{username}:{quote_plus(password)}"
    "@localhost:3306/sales_analysis_db"
)

with engine.connect() as connection:
    print("MySQL connection successful!")

Enter your MySQL password:  ········

MySQL connection successful!

In [127]:
df.to_sql(
    name="Orders",
    con=engine,
    if_exists="fail",
    index=False,
    chunksize=1000
)

print("Cleaned data uploaded successfully!")

Cleaned data uploaded successfully!

C:\Users\saroj\AppData\Local\Temp\ipykernel_18116\2788088101.py:1: UserWarning: The provided table name 'Orders' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(